services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 30s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: generator
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./images:/app/images
      - ./dataset-face:/app/dataset-face
      - ./dataset-team:/app/dataset-team
      - ./results:/results

  consumer-face:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer-face
    restart: on-failure
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./dataset-face:/app/dataset-face
      - ./results:/results

  consumer-team:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer-team
    restart: on-failure
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./dataset-team:/app/dataset-team
      - ./results:/results
      - ./consumer_team.py:/app/consumer_team.py
    command: python3 consumer_team.py

networks:
  app_network:
    driver: bridge